name: New Command request
description: Ask for a new command
title: 'New Command : '
labels: ['feature']
body:
  - type: input
    attributes:
      label: Domain
      placeholder: modules, configuration, etc
    validations:
      required: false
  - type: input
    attributes:
      label: Command
      placeholder: disable, list, etc
    validations:
      required: true
  - type: input
    attributes:
      label: parameters
      description: describe each parameter.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Command description
      description: What does the command do ?
      placeholder: With this command you can ...
  - type: markdown
    attributes:
      value: |
        Additionnal informations
